
import { Inter } from "next/font/google";
import "./globals.css";
import Main from "./layout/main";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Turk Compass Admin Panel",
    description: "Generated by Turk Compass",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
            <Main>{children}</Main>
            </body>
        </html>
    );
}
